### ISSUE TITLE
No module named 'ete3'

### ISSUE THREAD

**Issue by sh1va73** [DedSecInside/TorBot#177]
I did a fresh install on latest Kali and get this error:
Traceback (most recent call last):
  File "torBot.py", line 10, in <module>
    from modules.analyzer import LinkTree
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "modules/analyzer.py", line 6, in <module>
    from ete3 import Tree, TreeStyle, TextFace, add_face_to_node
ModuleNotFoundError: No module named 'ete3'
[6494] Failed to execute script torBot

> I checked and ete3 is already installed but still get this error

**Comment by KingAkeem** [comment]
Which version of `pip` are you using? I just performed a fresh install on a Ubuntu machine with `v9.0.1` and python 3.6.

**Comment by PSNAppz** [comment]
@sh1va73 If you are using `python3` with `pip3` try running` pip3 install ete3`
otherwise with`pip try pip install ete3`

**Comment by disparata** [comment]
Since this is the very first google entry you will find when searching for this error, here is the solution:

As I wrote in [this answer](https://github.com/DedSecInside/TorBot/issues/198#issuecomment-782719814), the easy solution for this is to uninstall and then install the module again using pip3.

Just run 

`pip3 uninstall <your_module_name>`
`pip3 install <your_module_name>`

So here you should run

`pip3 uninstall ete3`
`pip3 install ete3`

I had to do this for several modules. See my other answer which I linked above.
