### ISSUE TITLE
ModuleNotFoundError: No module named 'modules'

### ISSUE THREAD

**Issue by Bilinmiyor81110** [DedSecInside/TorBot#198]
`Traceback (most recent call last):
  File "src/torBot.py", line 10, in <module>
    from modules.analyzer import LinkTree
ModuleNotFoundError: No module named 'modules'
[12782] Failed to execute script torBot
`
not fouding the 'modules'
why? and how to solve it?

**Comment by Individuum92** [comment]
Have you installed the python dependencies?

- beautifulsoup4
- pyinstaller
- PySocks
- termcolor
- requests
- requests_mock
- yatta

**Comment by disparata** [comment]
I ran into the same problem. I also had the error
`No module named 'ete3'`

The very easy solution for this is, to run the following commands **for every module which is causing problems**:
`pip3 uninstall <your_module_name>`
And then:
`pip3 install <your_module_name>`

So refering to your problem the module name should me "analyzer".

The problems are wrong paths and this will fix it. Run this for every module you encounter an error for.
Took me quite some time to figure out, but this will fix it perfectly and there is no need to deal with virtual environment (sometimes you don't want to use that).

Btw, in my case I had to run the following commands in order to get it working (first one will fix the ete3 module):

`pip3 uninstall PyQt5==5.11.3`
`pip3 install PyQt5==5.11.3`

`pip3 uninstall python-dotenv`
`pip3 install python-dotenv`

`pip3 uninstall threadsafe`
`pip3 install threadsafe`

`pip3 uninstall progress`
`pip3 install progress`

`pip3 uninstall validators`
`pip3 install validators`

`pip3 uninstall decorator`
`pip3 install decorator`
