### ISSUE TITLE
ImportError: cannot import name 'faces' from 'ete3'

### ISSUE THREAD

**Issue by DocKali** [DedSecInside/TorBot#238]
Hi there,

I installed the tool and everything went well, no error message during the process.

But when I try to run it, both via ./torBot and via /src python3 torBot.py, I get the following error:

```
Traceback (most recent call last):
  File "torBot.py", line 10, in <module>
    from modules.linktree import LinkTree
  File "/home/dockali/Tools/TorBot/src/modules/linktree.py", line 4, in <module>
    from ete3 import faces, Tree, TreeStyle, TextFace
ImportError: cannot import name 'faces' from 'ete3' (/usr/local/lib/python3.8/dist-packages/ete3/__init__.py)
```

Where can this error come from and how to fix it?

Thanks for your help !

**Comment by anoduck** [comment]
@DocKali I went with the Dockerized deployment, because I knew I was going to run into dependency issues during installation. This now appears to have been the more difficult approach, as the Dockerfile was not even ready for deployment, and was missing the required dependencies. Although, I am receiving a different error, I have the sneaky suspicion this project has fallen into a state of no longer being under active development. As the required dependencies listed in pyproject.toml are several versions behind what is now current.

**Comment by KingAkeem** [comment]
I'm not able to reproduce this, have you used `poetry` to install the dependencies? https://python-poetry.org/

**Comment by anoduck** [comment]
> I'm not able to reproduce this, have you used `poetry` to install the dependencies? https://python-poetry.org/

Make sure to use the new script when installing poetry, it will squawk at you if you don't. Simply execute:

```
curl -sSL https://install.python-poetry.org | python3 -
```

**Comment by parthk2510** [comment]
@anoduck Even after using this command I am having same  error. What should I do ? Also is there any video installation guide for this . It will be useful 
![Screenshot_2022-07-06_13-19-00](https://user-images.githubusercontent.com/87540263/177498788-0da81c17-153a-4499-ac7e-2024824ce09c.png)

**Comment by PSNAppz** [comment]
V2.1.0 has been released and the ete3 module was removed temporarily
